FROM python:3.11-slim

WORKDIR /app

COPY requirements ./requirements

RUN pip install --no-cache-dir     -r requirements/ui.txt

COPY app/ui app/ui

CMD ["streamlit", "run", "app/ui/app.py", "--server.port=8501", "--server.address=0.0.0.0"]
