FROM python:3.11-slim

WORKDIR /app

COPY requirements ./requirements

RUN python3 -m pip install --upgrade pip setuptools wheel && \
    python3 -m pip install \
    --no-cache-dir \
    --timeout 600 \
    --retries 15 \
    --prefer-binary \
    -r requirements/api.txt

COPY app app

CMD ["uvicorn", "app.api.main:app", "--host", "0.0.0.0", "--port", "8000"]
